import json


ROOM_LIST = [
    'THE FOUNDATION', 'ENTRANCE HALL', 'SPARE ROOM', 'ROTUNDA', 'PARLOR', 'BILLIARD ROOM', 'GALLERY',
    'ROOM 8', 'CLOSET', 'WALK-IN CLOSET', 'ATTIC', 'STOREROOM', 'NOOK', 'GARAGE', 'MUSIC ROOM', 'LOCKER ROOM', 'DEN',
    'WINE CELLAR', 'TROPHY ROOM', 'BALLROOM', 'PANTRY', 'RUMPUS ROOM',
    'VAULT', 'OFFICE', 'DRAWING ROOM', 'STUDY', 'LIBRARY', 'CHAMBER OF MIRRORS', 'THE POOL', 'DRAFTING STUDIO',
    'UTILITY CLOSET', 'BOILER ROOM', 'PUMP ROOM', 'SECURITY', 'WORKSHOP', 'LABORATORY', 'SAUNA',
    'COAT CHECK', 'MAIL ROOM', 'FREEZER', 'DINING ROOM', 'OBSERVATORY', 'CONFERENCE ROOM',
    'AQUARIUM', 'ANTECHAMBER', 'ROOM 46', 'BEDROOM', 'BOUDOIR', 'GUEST BEDROOM', 'NURSERY', "SERVANT'S QUARTERS",
    'BUNK ROOM', "HER LADYSHIP'S CHAMBER", 'MASTER BEDROOM', 'HALLWAY', 'WEST WING HALL', 'EAST WING HALL', 'CORRIDOR',
    'PASSAGEWAY', 'SECRET PASSAGE', 'FOYER', 'GREAT HALL', 'TERRACE',
    'PATIO', 'COURTYARD', 'CLOISTER', 'VERANDA', 'GREENHOUSE', 'MORNING ROOM', 'SECRET GARDEN',
    'COMMISSARY', 'KITCHEN', 'LOCKSMITH', 'SHOWROOM', 'LAUNDRY ROOM', 'BOOKSHOP', 'THE ARMORY',
    'MOUNT HOLLY GIFT SHOP', 'LAVATORY', 'CHAPEL', "MAID'S CHAMBER", 'ARCHIVES', 'GYMNASIUM',
    'DARKROOM', 'WEIGHT ROOM', 'FURNACE', 'DOVECOTE', 'THE KENNEL', 'CLOCK TOWER', 'CLASSROOM',
    'SOLARIUM', 'DORMITORY', 'VESTIBULE', 'CASINO', 'PLANETARIUM', 'CONSERVATORY', 'CLOSED EXHIBIT',
    'MECHANARIUM', 'LOST AND FOUND', 'TREASURE TROVE', 'TUNNEL', 'THRONE ROOM', 'THRONE OF THE BLUE PRINCE',
    'HOVEL', 'ROOT CELLAR', 'SCHOOLHOUSE', 'SHELTER', 'SHRINE', 'TOMB', 'TOOLSHED', 'TRADING POST'
]

with open ('.\\jsons\\directory.json', 'r') as f:
    DIRECTORY = json.load(f)

ROOM_LOOKUP = {}
for type, rooms in DIRECTORY["FLOORPLANS"].items():
    for room, characteristics in rooms.items():
        ROOM_LOOKUP[room] = characteristics